<link href="<?php echo base_url()?>assets/front/css/podcast.css?rand=<?=rand();?>" rel="stylesheet" />
<link href="<?php echo base_url()?>assets/front/css/newcampaign.css?r=<?=rand();?>" rel="stylesheet" />
<link href="<?php echo base_url()?>assets/front/fullpage/fullpage.css?rand=<?=rand();?>" rel="stylesheet" />
<div class='min-height page-newcampaign'>
	<div class='container'>
	<div class='bg-article-'>
		<div class='row'>
			<div class='col-sm-12'>
			</div>
			<div class='col-sm-8 col-sm-offset-2'>
				<h1>Kebijakan Privacy</h1>
<div style="mso-element: para--div; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm 0cm 0cm 0cm;">
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Autheticty adalah platform media dan komunitas sosial online di Jakarta, Indonesia. Kami menyediakan jasa berbagi konten secara online berdasarkan berbagai kepentingan individu atau kelompok (“<strong><span style=": ''; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Jasa</span></strong>”) melalui laman situs, aplikasi telepon seluler atau aplikasi komputer kami dan semua alat, data, perangkat lunak atau aplikasi terkait (“<strong><span style=": ''; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Platform</span></strong>”).</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami ingin anda tahu bahwa ketika anda menggunakan Jasa yang disediakan oleh Autheticty, kami dapat mengumpulkan berbagai jenis informasi dan data dari atau tentang anda. Autheticty bermaksud untuk membantu anda memahami jenis informasi yang kami kumpulkan, bagaimana kami menggunakannya dan pilihan apa yang anda miliki dan kami mengatur Kebijakan Privasi penggunaan laman sitas ini (“<strong><span style=": ''; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Kebijakan Privasi</span></strong>”).</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kebijakan Privasi, beserta Syarat dan Ketentuan kami dan setiap istilah lain yang secara khusus disebutkan pada salah satu dokumen tersebut, merupakan perjanjian yang mengikat secara sah (“<strong><span style=": ''; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Perjanjian</span></strong>”) antara anda dan Autheticty berkenaan dengan penggunaan Jasa atau Platform oleh anda.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Informasi yang Anda berikan</span></strong><span class="apple-converted-space"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">&nbsp;</span></strong></span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Ketika anda mendaftar dengan tujuan untuk menggunakan jasa kami, anda akan secara sukarela memberikan kepada kami beberapa informasi tertentu. Anda juga memberikan informasi ketika anda membuat, membagi, mengirim pesan, mengunggah, atau berkomunikasi dengan para pengguna yang lain, dan ketika anda melakukan aktivitas lain dengan Jasa kami. Informasi ini meliputi konten yang anda berikan, nama, alamat email, foto, tanggal, video, audio termasuk setiap informasi yang lain. Para pengguna yang menggunakan telepon seluler untuk menggunakan Jasa juga dapat menyediakan informasi yang lain seperti data lokasi, informasi kontak, dan informasi lain yang didapatkan dari program-program telepon seluler. Kami juga mengumpulkan informasi tentang bagaimana anda menggunakan Jasa kami, seperti jenis Konten yang Anda lihat atau yang anda buka atau frekuensi dan durasi aktivitas anda.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Anda juga dapat memberikan ijin kepada kami untuk mengakses informasi anda pada jasa-jasa yang lain. Sebagai contoh, anda dapat membuat link dari akun-akun anda yang lain, termasuk dan tidak terbatas, dari Facebook, Twitter, Instagram, dan akun sosial media lain yang mungkin ada di masa mendatang, ke Autheticty, yang memungkinkan kami untuk mendapatkan informasi dari akun-akun tersebut (seperti teman atau kontak anda). Informasi yang kami dapatkan dari jasa-jasa tersebut sering bergantung pada pengaturan anda atau kebijakan privasi jasa-jasa tersebut, jadi pastikan untuk memeriksa kebijakan privasi jasa-jasa tersebut.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Bagaimana kami menggunakan informasi yang kami dapatkan.</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami menggunakan informasi yang kami dapatkan dari semua Jasa untuk menyediakan, menjaga, melindungi dan meningkatkan Jasa, untuk mengembangkan Jasa yang baru, dan untuk melindungi Autheticty dan para pengguna kami.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami juga menggunakan informasi yang kami dapatkan untuk menawarkan konten yang diatur, seperti merekomendasikan topik pengguna lain yang mungkin menarik bagi anda (sebagai contoh, apabila anda telah menunjukkan bahwa anda tertarik dengan perjalanan untuk berwisata dan anda mengunjungi laman situs perjalanan, kami dapat menyarankan topik terkait Perjalanan) dan juga iklan atau bentuk produk yang lain yang kami rasa berkaitan dengan anda (sebagai contoh, apabila anda mengikuti topik yang berkaitan dengan gitar, kami dapat menunjukkan bagi anda iklan-iklan alat musik).</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami menggunakan informasi anda untuk mengirimkan kepada anda penawaran pemasaran yang berkaitan dengan hobi anda, untuk mengkomunikasikan kepada anda tentang Jasa kami, menawarkan kepada anda setiap informasi yang mungkin anda tertarik dan memberitahukan kepada anda kebijakan dan persyaratan kami. Kami juga menggunakan informasi anda untuk merespon anda ketika anda menghubungi kami. Yang terakhir, kami juga menghubungkan anda dengan teman-teman anda yang memiliki akun serta topik pada Autheticty. Misalnya, apabila anda mendaftar dengan menghubungkan akun Facebook, kami dapat membantu teman Facebook anda untuk menemukan akun Autheticty anda ketika mereka pertama kami mendaftar pada Autheticty.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami menggunakan informasi yang kami miliki untuk memverifikasi akun dan aktivitas, dan untuk menjaga keselamatan dan keamanan pada dan pada saat berhentinya Jasa kami, seperti dengan menyelidiki aktivitas yang mencurigakan atau pelanggaran terhadap persyaratan atau kebijakan kami serta setiap Undang-Undang dan peraturan yang berlaku. Kami berupaya keras untuk melindungi akun anda dengan memiliki tim ahli, sistem otomatis dan teknologi canggih seperti enkripsi dan pembelajaran mesin. Kami juga menawarkan alat keamanan yang mudah digunakan yang memberikan keamanan berlapis pada akun anda.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami juga dapat menggunakan informasi perorangan bagi salah satu afiliasi kami atau usaha atau orang-orang terpercaya yang lain untuk melakukan pemrosesan bagi kami, berdasarkan instruksi kami dan sesuai dengan Kebijakan Privasi kami serta upaya-upaya kerahasiaan dan keamanan yang lain yang sesuai.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Informasi teknis</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Ketika menggunakan Jasa kami, terdapat informasi yang akan dibuat dan dicatat secara otomatis. Autheticty juga akan mengumpulkan data-data yang terdiri dari:</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">• Data log. Ketika anda menggunakan Autheticty, server kami akan secara otomatis mencatat informasi (“<strong><span style=": ''; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">data log</span></strong>”), termasuk informasi yang dikirim oleh browser anda kapanpun anda mengunjungi suatu laman situs atau yang dikirimkan oleh aplikasi telepon seluler anda kapanpun ketika anda menggunakannya. Data log ini dapat mencakup alamat Protokol Internet anda, alamat laman-laman situs yang anda kunjungi yang memiliki fitur Autheticty, jenis dan pengaturan browser, tanggal dan waktu permintaan anda, bagaimana anda menggunakan Autheticty, dan data cookie.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">• Data cookie. Bergantung pada bagaimana anda mengakses Jasa kami, kami dapat menggunakan “cookie” (file teks kecil yang dikirimkan oleh komputer anda setiap kali anda mengujungi laman situs kami, yang khas bagi akun Autheticty atau browser anda) atau teknologi serupa untuk mencatat data log. Ketika kami menggunakan cookie, kami dapat menggunakan cookie “sesi” (yang berakhir sampai anda menutup browser anda) atau cookie “persisten” (yang berakhir sampai anda atau browser anda menghapusnya). Sebagai contoh, kami dapat menggunakan cookie untuk menyimpan preferensi bahasa anda atau pengaturan Autheticty anda yang lain sehingga anda tidak perlu mengaturnya setiap kali anda mengunjungi Autheticty. Beberapa cookie yang kami gunakan berkaitan dengan akun Autheticty anda (termasuk informasi pribadi tentang anda, seperti alamat email yang anda berikan), dan cookie yang lain tidak.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">• Informasi alat. Selain data log, kami juga dapat mengumpulkan informasi tentang alat yang anda gunakan ketika anda menggunakan Autheticty, termasuk jenis alat, sistem operasi apa yang anda gunakan, pengaturan alat, pengidentifikasi alat yang khas, dan data crash. Baik kami mengumpulkan beberapa atau semua informasi tersebut, akan bergantung pada jenis alat apa yang anda gunakan dan pengaturannya. Sebagai contoh, jenis informasi yang berbeda tersedia bergantung pada apakah anda menggunakan Mac atau PC, atau iPhone atau android. Untuk mengetahui lebih banyak informasi apa yang disediakan oleh alat anda bagi kami, silahkan periksa kebijakan produsen alat atau provider perangkat lunak anda.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Informasi yang kami bagikan</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami tidak membagikan informasi perorangan kepada perusahaan, organisasi atau individu di luar Autheticty kecuali dalam salah satu dari kondisi-kondisi berikut:</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">• Dengan persetujuan anda</span></strong><span class="apple-converted-space"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">&nbsp;</span></strong></span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami dapat membagikan informasi pribadi anda kepada perusahaan, organisasi atau individu di luar Autheticty ketika kami mendapatkan ijin dari anda untuk melakukan hal tersebut. Kami meminta persetujuan anda untuk membagikan atau menyebarkan setiap informasi pribadi yang sensitif.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">• Karena alasan hukum</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami akan membagikan informasi pribadi anda kepada perusahaan, organisasi atau individu di luar Autheticty apabila kami memiliki keyakinan dengan itikad baik bahwa akses, penggunaan, penjagaan atau pengungkapan informasi tersebut secara wajar diperlukan untuk:</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">o Mematuhi Undang-Undang, peraturan, proses hukum yang berlaku atau permintaan pemerintah dan perintah pengadilan yang dapat diberlakukan.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">o Memberlakukan Syarat dan Ketentuan yang berlaku, termasuk penyelidikan kemungkinan pelanggaran atau terjadinya salah satu pelanggaran setelah laporan yang kami terima.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">o Mendeteksi, mencegah atau menyasar penipuan, pelanggaran keselamatan atau permasalahan teknis.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">o Perlindungan dari bahaya, hak, properti atau kesalamatan Autheticty, para pengguna kami atau publik sebagaimana yang disyaratkan atau diperkenankan oleh Undang-Undang dan peraturan yang berlaku.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami dapat terlibat dalam perkara penggabungan, konsolidasi, akuisisi, perkara kepailitan, penundaan kewajiban pembayaran utang (PKPU), pembubaran atau likuidasi, restrukturisasi atau transaksi atau perkara serupa yang melibatkan pengungkapan informasi yang dijelaskan pada Kebijakan Privasi ini.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami bekerja sama dengan perusahaan pihak ketiga yang membantu kami menyediakan dan meningkatkan Jasa kami atau yang menggunakan iklan atau produk terkait yang membuatnya dapat mengoperasikan perusahaan kami dan menyediakan jasa gratis bagi orang-orang di seluruh dunia.</span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Jenis pihak ketiga yang kami dapat membagikan informasi tentang anda dengan persetujuan anda adalah Jasa Iklan, Pengukuran dan Jasa Analisis dan Para Vendor, penyedia jasa dan mitra yang lain. Pihak ketiga yang kepadanya kami dapat mengungkapkan informasi pribadi anda mungkin memiliki kebijakan privasi tersendiri yang menjelaskan bagaimana mereka menggunakan dan mengungkapkan informasi pribadi. Kebijakan ini akan mengatur penggunaan, pengurusan dan pengungkapan informasi pribadi anda ketika kami membagikannya dengan pihak tersebut sebagaimana yang dijelaskan pada Kebijakan Privasi ini. Apabila anda ingin mengetahui lebih banyak tentang praktik kebijakan mereka, kami menyarankan anda untuk mengunjungi laman situs yang terkait.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Pilihan apa yang anda miliki tentang informasi pribadi anda?</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Dengan tujuan untuk mengendalikan informasi anda, apabila anda memiliki akun Autheticty, anda dapat mengakses dan mengubah informasi pada profil anda pada setiap waktu, dan mengubah pengaturan privasi akun anda. Anda dapat menghubungkan akun Autheticty anda dengan jasa-jasa yang lain. Anda juga dapat menutup akun anda pada setiap waktu. Ketika anda menutup akun anda, kami akan menonaktifkan akun tersebut dan menghapus setiap informasi yang berkaitan dengan akun anda. Kami dapat menyimpan salinan arsip informasi anda sebagaimana yang disyaratkan oleh Undang-Undang dan peraturan yang berlaku dan untuk tujuan usaha yang sah (termasuk untuk membantu mengatasi permasalahan penipuan dan spam).</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Kebijakan kami tentang informasi anak-anak</span></strong><span class="apple-converted-space"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">&nbsp;</span></strong></span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Autheticty tidak ditujukan bagi anak-anak di bawah usia 18 tahun. Apabila anda mengetahui bahwa anak-anak anda yang di bawah umur menyediakan bagi kami informasi pribadi tanpa ijin anda, silakan hubungi kami.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Perubahan kebijakan ini</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kami dapat mengubah kebijakan ini dari waktu ke waktu (baik dengan maksud kami sendiri atau sebagaimana yang disyaratkan oleh Undang-Undang), dan apabila kami mengubahnya, kami akan mengunggah setiap perubahan pada laman ini. Apabila anda tetap menggunakan Autheticty setelah perubahan tersebut berlaku, secara otomatis anda setuju terhadap kebijakan yang telah direvisi tersebut. Apabila perubahan tersebut signifikan, kami dapat tetapi tidak berkewajiban untuk menyampaikan pemberitahuan sebelumnya kepada anda atau meminta persetujuan anda melalui respon aktif.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Keterpisahan</span></strong><span class="apple-converted-space"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">&nbsp;</span></strong></span></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Apabila salah satu atau lebih ketentuan Kebijakan Privasi ini dinyatakan tidak sah, batal atau tidak dapat diberlakukan, ketentuan tersebut harus dianggap terpisah dan tidak akan mempengaruhi validitas dan/atau keberlakukan ketentuan-ketentuan Kebijakan Privasi yang lain, yang tetap memiliki kekuatan hukum penuh dan berlaku.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Keseluruhan Perjanjian</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kebijakan Privasi ini, beserta dengan Syarat dan Ketentuan, merupakan keseluruhan perjanjian antara anda dan Autheticty berkenaan dengan penggunaan anda terhadap Jasa atau Platform.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Pengalihan kepada Pihak Ketiga</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kebijakan Privasi ini, dan setiap hak dan lisensi yang diberikan berdasarkan Kebijakan Privasi ini, tidak boleh dialihkan oleh anda tanpa persetujuan Autheticty terlebih dahulu, tetapi dapat dialihkan oleh Autheticty kepada setiap pihak tanpa batasan.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Pengesampingan</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Pengesampingan terhadap setiap persyaratan Kebijakan Privasi ini tidak boleh dianggap sebagai pengesampingan selanjutnya atau pengesampingan yang berlanjut atas persyaratan tersebut atau persyaratan yang lain, dan keterlambatan atau kegagalan Autheticty untuk menggunakan setiap hak atau ketentuan berdasarkan Syarat dan Ketentuan bukan merupakan pengesampingan atas hak atau ketentuan tersebut.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Bahasa</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kebijakan Privasi ini ditampilkan baik dalam Bahasa Inggris maupun Bahasa Indonesia. Keduanya sah dan merupakan dokumen yang sama.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Hukum Yang Mengatur</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Kebijakan Privasi ini harus diatur dan ditafsirkan sesuai dengan Undang-Undang Republik Indonesia.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Penyelesaian Perselisihan</span></strong></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Setiap perselisihan yang timbul dari atau berkenaan dengan Kebijakan Privasi ini, termasuk tanpa batasan setiap pertanyaan tentang keberadaan, validitas atau pengakhirannya, yang tidak dapat diselesaikan secara damai, harus diselesaikan melalui arbitrase berdasarkan aturan-aturan administratif dan prosedural arbitrase Badan Arbitrase Nasional Indonesia (“<strong><span style=": ''; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">BANI</span></strong>”) yang berlaku saat itu. Arbitrator tunggal harus ditunjuk untuk memimpin perkara Arbitrase. Apabila para pihak tidak menyepakati arbitrator tunggal dalam waktu 7 (tujuh) hari sejak pemberitahuan oleh Ketua BANI mengenai penunjukkan arbiter tunggal yang dipilih para pihak, para pihak setuju bahwa arbitrator tunggal tersebut akan ditunjuk oleh BANI.</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 10.5pt; : ''; color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Pemberitahuan:</span></strong></p>
<p style="margin-top: 0cm; margin-right: 0cm; margin-bottom: 15.0pt; margin-left: 0cm; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;">Anda setuju untuk menerima semua komunikasi termasuk pemberitahuan, perjanjian, pengungkapan, atau informasi lain dari Autheticty secara elektronik. Autheticty dapat menyediakan semua komunikasi tersebut melalui email atau dengan mengunggahnya pada Jasa Autheticty. Untuk pertanyaan terkait, anda dapat menghubungi kami. Anda juga dapat menyampaikan pemberitahuan terkait hukum kepada Autheticty ke info@authenticity.id</span></p>
<p style="margin: 0cm; margin-bottom: .0001pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 10.5pt; : ''; color: #363636;"><br> Tidak terdapat ketentuan apapun pada Kebijakan Privasi ini yang membatasi hak Autheticty untuk mengajukan keberatan atas panggilan sidang, klaim atau gugatan lainnya.</span></p>
</div>
			</div>
		</div>
	</div>
	</div>
</div>

<?php $this->load->view('front/podcast/footerfp');?>
<script>
	$(document).on('ready', function() {

	});
</script>
