<link href="<?php echo base_url()?>assets/front/css/podcast.css?rand=<?=rand();?>" rel="stylesheet" />
<link href="<?php echo base_url()?>assets/front/css/newcampaign.css?r=<?=rand();?>" rel="stylesheet" />
<link href="<?php echo base_url()?>assets/front/fullpage/fullpage.css?rand=<?=rand();?>" rel="stylesheet" />
<div class='min-height page-newcampaign'>
	<div class='container'>
	<div class='bg-article-'>
		<div class='row'>
			<div class='col-sm-12'>

			</div>
			<div class='col-sm-8 col-sm-offset-2'>
			<h1>Term & Condition</h1>
<div>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Authenticity adalah platform media dan komunitas sosial online. Authenticity menyediakan sebuah jasa untuk berbagi konten secara online melalui seluruh platform Authenticity (laman situs dan laman situs seluler). Pada laman ini, mengatur "<strong><span style=": solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Syarat dan Ketentuan</span></strong>" dalam penggunaan jasa dan platform Authenticity. Syarat dan Ketentuan ini merupakan sebuah perjanjian yang mengikat secara sah antara Anda, selaku Pengguna dan Authenticity berkenaan dengan penggunaan jasa dan platform Authenticity oleh Anda. Dengan mengakses atau menggunakan jasa atau platform Authenticity, berarti Anda menyetujui Syarat dan Ketentuan ini dan Anda menyatakan serta menjamin bahwa Anda telah membaca dan memahaminya. Apabila Anda tidak setuju dengan Syarat dan Ketentuan ini, harap Anda tidak mengakses atau menggunakan jasa atau platform Authenticity.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Pendaftaran dan Penggunaan Situs ini oleh Anda</span></strong></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636;">&nbsp;</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Jasa dan platform Authenticity dimaksudkan khusus untuk yang berusia&nbsp;<strong><span style=": solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">18 tahun</span></strong>&nbsp;atau lebih yang bertempat tinggal di&nbsp;<strong><span style=": solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Indonesia</span></strong>. Ketika Anda ingin mendaftarkan diri ke dalam Authenticity, anda harus memberikan beberapa informasi seperti nama, tanggal lahir, dan alamat e-mail serta nomor ponsel yang aktif. Aneka informasi Anda dapat digunakan untuk tujuan komunikasi, promosi, dan penawaran yang terkait dengan produk-produk Authenticity melalui sarana elektronik atau sarana lainnya (SMS). Anda dapat menggunakan jasa atau platform Authenticity hanya apabila anda setuju untuk membuat kontrak yang terikat sebagaimana dimaksud di dalam Syarat dan Ketentuan ini. Anda dapat menyetujui kontrak tersebut dengan cara mengklik tombol penerimaan Syarat dan Ketentuan yang muncul pada saat Anda melakukan registrasi.</span></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Perubahan Syarat dan Ketentuan</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Atas kebijakan tunggalnya, Authenticity dapat mengubah atau merevisi Syarat dan Ketentuan setiap saat, dan dengan menggunakan jasa dan platform Authenticity, Anda secara otomatis setuju untuk terikat dengan perubahan atau revisi tersebut.</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Penggunaan Materi atau Konten dari Situs ini</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Platform Authenticity dan semua isinya adalah hak milik Authenticity, atau para pemberi lisensinya, dan dilindungi oleh undang-undang hak cipta, merek dagang, undang-undang lain terkait hak kekayaan intelektual, dan undang-undang lainnya di Indonesia. Dengan memasang materi atau konten Anda pada platform Authenticity, Anda telah memberikan lisensi non-eksklusif, bebas-royalti, terbatas hanya untuk tujuan pengoperasian dan penggunaan jasa serta platform Authenticity saja. Lisensi ini dapat digunakan untuk menyimpan, menampilkan, memodifikasi, dan mendistribusikan konten milik Anda pada Authenticity, dan hal ini sepenuhnya dilakukan hanya untuk tujuan pengoperasian dan penggunaan jasa serta platform Authenticity saja. Authenticity juga berhak untuk menghapus atau memodifikasi materi atau konten pengguna dengan alasan apapun, khususnya materi atau konten pengguna yang melanggar Syarat dan Ketentuan ini.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Peraturan Mengenai Hak Kekayaan Intelektual</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Authenticity mewajibkan para penggunanya untuk menghargai hak kekayaan intelektual antar pengguna. Para pengguna tidak boleh melakukan segala hal yang terkait tentang menyalin atau membuat ulang, pendistribusian, dan eksploitasi setiap materi atau konten untuk tujuan apapun tanpa persetujuan tertulis terlebih dahulu dari sang pemilik asli materi atau konten (pengguna lain).</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Pernyataan dan Jaminan</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Para pengguna yang mengakses atau menggunakan jasa atau platform Authenticity dengan ini menyatakan dan menjamin seluruh hal-hal berikut:</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >i. Seluruh materi dan konten setiap pengguna adalah karya asli, atau sang pengguna telah mendapatkan semua hak, lisensi, persetujuan dan ijin yang diperlukan untuk dapat menggunakan materi dan konten tersebut;</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >ii. Seluruh materi dan konten setiap pengguna adalah sepenuhnya tanggung jawab dari pengguna. Maka, pengguna menjamin dan membebaskan Authenticity dari segala bentuk kewajiban, tanggungjawab, termasuk dan tidak terbatas apabila ada tuntutan, baik tuntutan hukum, ganti rugi, dan tuntutan lain dari pihak manapun atas materi dan konten yang telah diunggah di dalam platform Authenticity;</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >iii. Pengguna yang memiliki materi atau konten yang merupakan karya asli, atau sudah didapatkan hak, ijin, atau lisensi tersebut memberikan wewenang kepada Authenticity untuk menggunakan, mengunggah, membuat ulang, mendistribusikan, menampilkan kepada publik, menyediakan, dan mengkomunikasikan materi atau konten pengguna kepada publik melalui platform Authenticity;</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >iv. Pengguna telah mendapatkan setiap dan semua persetujuan, ijin dan/atau pelepasan yang diperlukan dari setiap dan semua orang yang muncul pada konten Anda untuk memasukkan nama, suara, kinerja atau kesukaan mereka pada konten Anda dan untuk mempublikasikannya pada platform dan melalui jasa yang terhubung dengan Authenticity;</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >v. Materi atau konten pengguna, termasuk setiap komentar yang Anda posting pada platform Authenticity, tidak dan tidak akan melanggar hukum, ofensif, bersifat kekerasan, kejahatan, merusak, cabul, rasis, eksplisit secara seksual, ofensif secara etnis atau budaya, melecehkan, yang mendukung kekerasan, terorisme, atau tindakan yang melawan hukum, mendorong kebencian atas dasar ras, jenis kelamin, agama dan/atau orientasi seksual;</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >vi. Pengguna dilarang untuk menggunakan platform Authenticity untuk tujuan politik, termasuk dan tidak terbatas untuk tidak memasukkan konten yang sifatnya mengandung unsur politik, baik dalam bentuk tulisan, foto, video, dan bentuk lain yang berkaitan dengan konten Pengguna di dalam platform Authenticity.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >vii. Materi atau konten pengguna tidak dan tidak akan menciptakan kewajiban apapun pada Authenticity, sponsor, para pemilik modal, anak perusahaan, afiliasi, penerus dan penerima pengalihan Authenticity, dan masing-masing karyawan, agen, direktur, komisaris, pejabat dan/atau para pemegang sahamnya.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Authenticity memegang hak untuk menghapus konten setiap pengguna, memberhentikan sementara atau mengakhiri akses terhadap jasa dan platform Authenticity, termasuk dan tidak terbatas mengambil jalur hukum apabila salah satu dari materi atau konten pengguna diyakini telah melanggar hak orang lain atau melanggar setiap hukum, aturan atau peraturan manapun, dan melanggar baik sebagian atau seluruh ketentuan yang telah diatur dan sepakati pengguna di dalam Syarat dan Ketentuan ini.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Pembatasan Tanggung Jawab dan Kewajiban</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Risiko dari penggunaan situs ini oleh Anda merupakan tanggung jawab Anda sendiri. Authenticity dan pihak-pihak afiliasinya secara tegas melepas tanggung jawab atas semua jenis jaminan, baik yang dinyatakan secara tegas maupun tersirat. Anda juga menjamin bahwa materi atau konten yang terdapat dalam situs ini tidak melanggar hak cipta dan seluruh hak kekayaan intelektual; bahwa akses terhadap situs ini tidak akan mengalami gangguan atau bebas dari kesalahan; bahwa situs ini akan aman; bahwa situs ini atau server-server yang digunakan untuk penyediaan situs ini akan bebas dari virus; atau bahwa informasi yang terdapat dalam situs ini akan bersifat lengkap, akurat, atau terkini. Apabila Anda mengunduh materi apa pun dari situs ini, Anda melakukannya atas kebijaksanaan dan risiko Anda sendiri. Setiap kerusakan yang terjadi pada sistem komputer Anda atau kehilangan data yang disebabkan oleh pengunduhan materi tersebut akan menjadi tanggung jawab Anda. Selain itu, Anda juga menanggung seluruh biaya untuk semua servis, reparasi atau perbaikan yang diperlukan atas segala kerusakan yang diakibatkan oleh Anda, untuk setiap hal yang Anda lakukan di dalam platform Authenticity. Anda memahami dan menyetujui bahwa Authenticity, maupun perusahaan-perusahaan afiliasi, anak-anak perusahaan masing-masing tidak bertanggung jawab atas ganti rugi yang bersifat langsung, maupun tidak langsung yang diakibatkan atau terkait oleh penggunaan atau tidak dapat digunakannya situs ini oleh Anda selaku pengguna, atau karena setiap tindakan yang dilakukan oleh Authenticity atau kelalaian Authenticity untuk melakukan tindakan sebagai akibat dari komunikasi Anda dengan Authenticity.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Ganti Rugi</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Sejauh diperkenankan oleh hukum yang berlaku, Anda setuju untuk membela, mengganti rugi dan membebaskan Authenticity, setiap induk perusahaan, pemegang saham, sponsor, pemilik modal, mitra usaha, direktur, komisaris, karyawan dan agen, dari dan terhadap setiap dan semua klaim, kerusakan, kewajiban, kerugian, tanggung jawab, biaya atau hutang dan pengeluaran yang timbul dari: (i) penggunaan atau akses Anda terhadap Authenticity; (ii) pelanggaran terhadap salah satu persyaratan Syarat dan Ketentuan oleh Anda; (iii) pelanggaran oleh Anda terhadap hak pihak ketiga, termasuk tanpa batasan, hak cipta, properti atau hak privasi; atau (iv) setiap klaim bahwa materi atau konten milik Anda menyebabkan kerusakan pada pihak ketiga. Kewajiban pembelaan dan pemberian ganti rugi ini akan tetap berlaku menurut Syarat dan Ketentuan ini dan selama Anda menggunakan jasa dan platform Authenticity.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Ganti rugi tersebut termasuk ganti rugi untuk kesalahan, kelalaian, gangguan, kecacatan, ketidaksesuaian, keterlambatan, virus komputer, kehilangan keuntungan, kehilangan data yang Anda alami, akses tanpa izin terhadap atau perubahan atas transmisi dan data Anda, serta kerugian-kerugian berwujud dan tidak berwujud lainnya.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Hukum yang Mengatur</span></strong></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Authenticity menggunakan Hukum Indonesia sebagai dasar yang mengatur Syarat dan Ketentuan penggunaan jasa dan platform Authenticity oleh Anda. Anda yang bertempat tinggal di Indonesia, diwajibkan menyetujui segala hukum eksklusif yang mengatur dari pengadilan-pengadilan Indonesia untuk setiap tindakan hukum untuk memberlakukan Syarat dan Ketentuan penggunaan ini.</span></p>
<p class="MsoNormal" style="margin-bottom: 15.0pt; text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >&nbsp;</span></p>
<p class="MsoNormal" style="mso-outline-level: 3; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><strong><span style="font-size: 18.0pt;  mso-fareast- mso-bidi- color: #363636; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm;">Hubungi Kami</span></strong></p>
<p class="MsoNormal" style="text-align: justify; text-justify: inter-ideograph; line-height: 18.9pt; : none; mso--alt: solid windowtext .25pt; padding: 0cm; mso-padding-alt: 0cm 0cm 0cm 0cm;"><span >Dengan ini Anda setuju untuk menerima segala macam komunikasi (pemberitahuan, perjanjian, pengungkapan, dan lainnya) dari Authenticity. Anda dapat menghubungi Authenticity dengan seputar pertanyaan yang mungkin ingin Anda ajukan mengenai Syarat dan Ketentuan pada fitur bantuan di dalam platform Authenticity.<br> </span><a href="https://www.authenticity.id/info@authenticity.id"><span style="font-size: 10.5pt;  mso-bidi- color: #1946ba; : solid windowtext 1.0pt; mso--alt: solid windowtext .25pt; padding: 0cm; text-decoration: none; text-underline: none;">info@authenticity.id</span></a></p>
</div>
			</div>
		</div>
	</div>
	</div>
</div>

<?php $this->load->view('front/podcast/footerfp');?>
<script>
	$(document).on('ready', function() {

	});
</script>
